backend/HospitalFinder/urls.py
from django.contrib import admin
from django.urls import path


from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HOME, name='home'),
    path('doctor/', include('doctor.urls')),
    path('hospital/', include('hospital.urls')),
    path('specialty/', include('specialty.urls')),
]

backend/doctor/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path("", views.index, name="index"),
]

backend/hospital/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path("", views.index, name="index"),
	path("Json_Response", views.Json_Response, name="Json_Response"),
	path("<int:hospital_id>/Json_Response", views.Json_Response_Id, name="Json_Response_Id"),
]

backend/specialty/urls.py
from django.urls import path
from . import views

app_name = 'specialty'

urlpatterns = [
	path("", views.index, name="specialty"),
	path("<int:specialty_id>/view_hospitals", views.hospitals, name="hospitals"),
	path("<int:specialty_id>/Hospital_Json_Response", views.Hospital_Json_Response, name="Hospital_Json_Response"),
	# path("<int:specialty_id>/Doctor_Json_Response", views.Doctor_Json_Response, name="Hospital_Json_Response"),
	path("Json_Response", views.Json_Response, name="Json_Response"),
]

backend/app/models.py
from django.db import models

# Create your models here.

backend/doctor/models.py
from django.db import models
from specialty.models import Specialty

# Create your models here.
class Doctor(models.Model):
	name = models.CharField(max_length=75)
	qualification = models.CharField(max_length=300, null=True)
	education = models.CharField(max_length=300, null=True)
	experience = models.CharField(max_length=300, null=True)
	opening_time = models.TimeField(null=True)
	closing_time = models.TimeField(null=True)
	specialty = models.ForeignKey(Specialty, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

backend/hospital/models.py
from django.db import models
from doctor.models import Doctor
from specialty.models import Specialty

# Create your models here.
class Hospital(models.Model):
	name = models.CharField(max_length=75, null=True)
	location = models.CharField(max_length=300, null=True)
	contact = models.CharField(max_length=50, null=True)
	doctor = models.ManyToManyField(Doctor)
	specialty = models.ManyToManyField(Specialty)

	def __str__(self):
		return self.name

backend/specialty/models.py
from django.db import models

# Create your models here.
class Specialty(models.Model):
	name = models.CharField(max_length=75)

	def __str__(self):
		return self.name

backend/HospitalFinder/views.py
from django.shortcuts import render, redirect


def HOME(request):
    return render(request, 'base.html')

backend/app/views.py
from django.shortcuts import render

# Create your views here.

backend/doctor/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Doctor

# Create your views here.
def index(request):
	doctors = Doctor.objects.all();
	context = {
		"doctors": doctors,
	}
	return render(request, "doctor/index.html", context);

backend/hospital/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse

from .models import Hospital

# Create your views here.
def index(request):
	hospitals = Hospital.objects.all()
	context = {
		"hospitals": hospitals,
	}
	return render(request, "hospital/index.html", context)

def Json_Response_Id(request, hospital_id):
	obj = Hospital.objects.get(pk=hospital_id)

	data = []

	hospital = {
		'id': obj.id,
		'name': obj.name,
		'location': obj.location,
		'contact': obj.contact,
	}

	doctors = []
	for doctor in obj.doctor.all():
		doctors.append({
			'id' : doctor.id,
			'name' : doctor.name,
			'qualification' : doctor.qualification,
			'experience' : doctor.experience,
			'education' : doctor.education,
			'opening_time' : doctor.opening_time,
			'closing_time' : doctor.closing_time,
		})

	hospital['doctors'] = doctors

	data.append(hospital)

	return JsonResponse(data, safe=False, json_dumps_params={'indent': 2})

def Json_Response(request):
	hospitals = Hospital.objects.all()

	data = []

	for obj in hospitals:
		hospital = {}
		hospital['id'] = obj.id
		hospital['name'] = obj.name
		hospital['location'] = obj.location
		hospital['contact'] = obj.contact

		for doctor in obj.doctor.all():
			doctors = {}
			doctors['id'] = doctor.id
			doctors['name'] = doctor.name
			doctors['qualification'] = doctor.qualification
			doctors['experience'] = doctor.experience
			doctors['education'] = doctor.education
			doctors['opening_time'] = doctor.opening_time
			doctors['closing_time'] = doctor.closing_time

		hospital['doctors'] = doctors

		data.append(hospital)

	return JsonResponse(data, safe=False, json_dumps_params={'indent': 2})

backend/specialty/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse

from .models import Specialty
from hospital.models import Hospital

# Create your views here.
def index(request):
	specialties = Specialty.objects.all();
	context = {
		"specialties": specialties,
	}
	return render(request, "specialty/index.html", context);

def hospitals(request, specialty_id):
	specialty = Specialty.objects.get(pk=specialty_id)
	hospitals = specialty.hospital_set.all()
    
	context = {
		"hospitals": hospitals,
	}
	return render(request, "specialty/hospitals.html", context);

# def Hospital_Json_Response(request, specialty_id):
#     specialty = Specialty.objects.get(pk=specialty_id)
#     hospitals = specialty.hospital_set.all()

#     data = {}
#     for obj in hospitals:
#         hospital = {
#             'id': obj.id,
#             'name': obj.name,
#         }
#         data[obj.id] = hospital

#     return JsonResponse(data)

def Hospital_Json_Response(request, specialty_id):
    specialty = Specialty.objects.get(pk=specialty_id)
    hospitals = specialty.hospital_set.all()

    data = []
    for obj in hospitals:
        doctors = get_doctor(obj.doctor.all())
        hospital = {
            'id': obj.id,
            'name': obj.name,
            'location': obj.location,
            'contact': obj.contact,
            'doctors': doctors
        }
        data.append(hospital)

    return JsonResponse(data, safe=False, json_dumps_params={'indent': 2})

def get_doctor(doctors):
    
    doctors_data = []
    for doctor in doctors:
        doctors_data.append({
            'id': doctor.id,
            'name': doctor.name,
            'qualification': doctor.qualification,
            'experience': doctor.experience,
            'education': doctor.education,
            'opening_time': doctor.opening_time,
            'closing_time': doctor.closing_time,
            # Add more fields as needed
        })

    return doctors_data

def Json_Response(request):
	specialties = Specialty.objects.all()

	data = {}

	for obj in specialties:
		specialty = {}
		specialty['id'] = obj.id
		specialty['name'] = obj.name

		# for doctor in obj.doctors.all():
		# 	doctors = {}
		# 	doctors['id'] = doctor.id
		# 	doctors['name'] = doctor.name

		# specialty['doctors'] = doctors

		data[obj.id] = specialty

	return JsonResponse(data)

backend/doctor/templates/doctor/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{{doctors}}
</body>
</html>

backend/hospital/templates/hospital/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{{hospitals}}
	
</body>
</html>

backend/specialty/templates/specialty/doctors.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{{hospitals}}
	<table border="1" cellspacing="0" cellpadding="10">
		<tr>
			<th colspan="3">Hospitals</th>
		</tr>
		<tr>
			<th>id</th>
			<th>name</th>
			<th>action</th>
		</tr>
		{% for hospital in hospitals %}
		<tr>
			<td>{{hospital.id}}</td>
			<td>{{hospital.name}}</td>
			<td><a href="{% url 'doctors' hospital.id %}">View Doctors</a></td>
		</tr>
		{% endfor %}
	</table>
</body>
</html>

backend/specialty/templates/specialty/hospitals.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{{hospitals}}
	<table border="1" cellspacing="0" cellpadding="10">
		<tr>
			<th colspan="3">Hospitals</th>
		</tr>
		<tr>
			<th>id</th>
			<th>name</th>
			<th>action</th>
		</tr>
		{% for hospital in hospitals %}
		<tr>
			<td>{{hospital.id}}</td>
			<td>{{hospital.name}}</td>
			<td></td>
		</tr>
		{% endfor %}
	</table>
</body>
</html>

backend/specialty/templates/specialty/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	{{specialties}}
	<table border="1" cellspacing="0" cellpadding="10">
		<tr>
			<th colspan="3">Specialties</th>
		</tr>
		<tr>
			<th>id</th>
			<th>name</th>
			<th>action</th>
		</tr>
		{% for specialty in specialties %}
		<tr>
			<td>{{specialty.id}}</td>
			<td>{{specialty.name}}</td>
			<td><a href="{% url 'specialty:hospitals' specialty.id %}">View Hospital</a></td>
		</tr>
		{% endfor %}
	</table>
</body>
</html>

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

backend/templates/includes/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

backend/templates/includes/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>